---

- name: BOOST | check if boost is already installed
  stat:
    path: "{{ boost_install_dir }}/bin/boost"
  register: boost_exists

- name: BOOST | get from git repository
  git: repo="{{ boost_repo_url }}"
       dest="{{ boost_tmp }}"
       version="boost-{{ boost_version }}"
  when: not boost_exists.stat.exists
  register: boost_downloaded

- name: BOOST | Bootstrap Boost
  command: chdir={{ boost_tmp }} ./bootstrap.sh --prefix={{ boost_install_dir }}
  when: boost_downloaded.changed

- name: BOOST | Make Boost
  command: chdir={{ boost_tmp }} ./b2
  when: boost_downloaded.changed

- name: BOOST | Insall Boost
  become: yes
  command: chdir={{ boost_tmp }} ./b2 install
  when: boost_downloaded.changed

- name: BOOST | cleanup tmp dir
  become: true
  file:
    path: "{{ boost_tmp }}"
    state: absent
  when: boost_downloaded.changed

...
