---

- name: BOOST | check if boost is already installed
  stat:
    path: "{{ boost_install_dir }}/bin/boost"
  register: boost_exists

- name: BOOST | get from git repository
  git: repo="{{ boost_repo_url }}"
       dest="{{ boost_tmp }}"
       version="{{ boost_version }}"
  when: not boost_exists.stat.exists
  register: boost_downloaded

- name: BOOST | Bootstrap Boost
  command: chdir={{ boost_tmp }} ./bootstrap.sh --prefix={{ boost_install_dir }}
  when: boost_downloaded.changed

- name: BOOST | Make Boost
  command: chdir={{ boost_tmp }} ./b2
  when: boost_downloaded.changed

- name: BOOST | Insall Boost
  become: yes
  command: chdir={{ boost_tmp }} ./b2 install
  when: boost_downloaded.changed

# - name: GCC | add path to /etc/profile.d/gcc_path.sh
#   become: true
#   action: template src=gcc_path.sh.j2
#           dest="/etc/profile.d/gcc_path.sh"
#           mode=0644
#   when: gcc_install.changed

# - name: GCC | cleanup build dir
#   become: true
#   file:
#     path: "{{ gcc_build }}"
#     state: absent
#   when: gcc_install.changed

# - name: GCC | cleanup build
#   become: true
#   file:
#     path: "{{ gcc_build_dir }}"
#     state: absent
#   when: gcc_install.changed

# - name: GCC | cleanup tmp
#   become: true
#   file:
#     path: "{{ gcc_tmp }}"
#     state: absent
#   when: gcc_install.changed

...
